
orders:
  - destination: https://kubernetes.default.svc
    charts:
      - repository: https://github.com/helm/charts.git
        revision: master
        subpaths:
          - name: chaoskube_in
            path: stable/chaoskube
            namespace: default
            chartvalue: values.yaml
            chartdeploystrategy: Canary
          - name: charmuseum_in  
            path: stable/chartmuseum
            namespace: default
            chartvalue: values.yaml
            chartdeploystrategy: Canary
