
orders:
  - destination: https://kubernetes.default.svc
    charts:
      - repository: https://github.com/helm/charts.git
        revision: master
        subpaths:
          - name: chaoskube-in
            path: stable/chaoskube
            namespace: default
            chartvalue: values.yaml
            chartdeploystrategy: Canary

