
orders:
  - destination: https://kubernetes.default.svc
    charts:
      - repository: https://github.com/helm/charts.git
        revision: master
        subpaths:
          - name: incube_zooke
            path: incubator/zookeeper
            namespace: default
            chartvalue: values.yaml
            chartdeploystrategy: Canary
